require("scripts.event_handlers")
require("scripts.commands")
local jobs = require("scripts.jobs")
local workers = require("scripts.workers.workers")
local scheduler = require("scripts.scheduler")
local stations = require("scripts.stations")

script.on_init(function()
    jobs.on_init()
    workers.on_init()
    scheduler.on_init()
    stations.on_init()
end)
